# Generated by Django 2.2 on 2020-02-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('WTT', 'Womens T-shirts & Tanks'), ('WT', 'Womens Tops'), ('WOJ', 'Womens Outwear & Jackets'), ('WSC', 'Womens Sweaters & Cardigans'), ('WJ', 'Womens Jeans'), ('WL', 'Womens Leggings'), ('WP', 'Womens Pants'), ('WSS', 'Womens Skirts & Shorts'), ('WA', 'Womens Accessories'), ('WT', 'Womens Tops'), ('WHSS', ' Womans Hoodies and Sweat Shirts'), ('MTT', 'Mens T-shirts & Tanks'), ('MT', 'Mens Tops'), ('MOJ', 'Mens Outwear & Jackets'), ('MSC', 'Mens Sweaters & Cardigans'), ('MS', 'Mens Shirts'), ('MP', 'Mens Pants'), ('MA', 'Mens Accessories'), ('MHSS', 'Mens Hoodies and Sweat Shirts')], max_length=2),
        ),
    ]
