from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    ShowArt,
    ShowLG,
    ShowWT,
    ShowWOJ,
    ShowWSC,
    ShowWJ,
    ShowWL,
    ShowWP,
    ShowWSS,
    ShowWA,
    ShowWHSS,
    ShowWSP,
    ShowMTT,
    ShowMT,
    ShowMOJ,
    ShowMSC,
    ShowMS,
    ShowMP,
    ShowMA,
    ShowMHSS,
    ShowMSP,
    ShowUTT,
    ShowUT,
    ShowUHSS,
    ShowUOJ,
    ShowUSC,
    ShowUJ,
    ShowUL,
    ShowUP,
    ShowUSS,
    ShowUA,
    ShowUSP,
    ShowWTT,

)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('art', ShowArt.as_view(), name='art'),
    path('logos', ShowLG.as_view(), name='logos'),
    path('wtt', ShowWTT.as_view(), name='wtt'),
    path('wt', ShowWT.as_view(), name='wt'),
    path('woj', ShowWOJ.as_view(), name='woj'),
    path('wsc', ShowWSC.as_view(), name='wsc'),
    path('wj', ShowWJ.as_view(), name='wj'),
    path('wl', ShowWL.as_view(), name='wl'),
    path('wp', ShowWP.as_view(), name='wp'),
    path('wss', ShowWSS.as_view(), name='wss'),
    path('wa', ShowWA.as_view(), name='wa'),
    path('whss', ShowWHSS.as_view(), name='whss'),
    path('wsp', ShowWSP.as_view(), name='wsp'),
    path('mtt', ShowMTT.as_view(), name='mtt'),
    path('mt', ShowMT.as_view(), name='mt'),
    path('moj', ShowMOJ.as_view(), name='moj'),
    path('msc', ShowMSC.as_view(), name='msc'),
    path('ms', ShowMS.as_view(), name='ms'),
    path('mp', ShowMP.as_view(), name='mp'),
    path('ma', ShowMA.as_view(), name='ma'),
    path('mhss', ShowMHSS.as_view(), name='mhss'),
    path('msp', ShowMSP.as_view(), name='msp'),
    path('utt', ShowUTT.as_view(), name='utt'),
    path('ut', ShowUT.as_view(), name='ut'),
    path('uhss', ShowUHSS.as_view(), name='uhss'),
    path('uoj', ShowUOJ.as_view(), name='uoj'),
    path('usc', ShowUSC.as_view(), name='usc'),
    path('uj', ShowUJ.as_view(), name='uj'),
    path('ul', ShowUL.as_view(), name='ul'),
    path('up', ShowUP.as_view(), name='up'),
    path('uss', ShowUSS.as_view(), name='uss'),
    path('ua', ShowUA.as_view(), name='ua'),
    path('usp', ShowUSP.as_view(), name='usp'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]
